import ServiceClient from "./component/ServiceClient";
import EmployerSidebaHeaderComponent from "@/components/EmployerSidebaHeaderComponent";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Mua dịch vụ",
  description: "Generated by create next app",
};

const ServicePage = () => {
  return (
    <>
      <EmployerSidebaHeaderComponent>
        <div className="flex w-full items-center">
          <p className="text-lg font-semibold text-secondaryColor">
            Mua dịch vụ
          </p>
        </div>
      </EmployerSidebaHeaderComponent>
      <ServiceClient />
    </>
  );
};

export default ServicePage;
