import UpdateInfoClient from "./components/UpdateInfoClient";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: "Cập nhật thông tin | Project X",
    description: "Generated by create next app",
  };
const UpdateInfoPage = () => {
  return (
    <div className="bg-accent ">
      <UpdateInfoClient />
    </div>
  );
};

export default UpdateInfoPage;
