import { Metadata } from "next";
import CardAppliedJob from "./component/CardAppliedJob";
export const metadata: Metadata = {
  title: "Việc làm đã ứng tuyển | Project X",
  description: "Generated by create next app",
};
const AplliedJobsPage = () => {
  return (
    <div className="bg-accent min-h-screen">
      <CardAppliedJob />;
    </div>
  );
};

export default AplliedJobsPage;
