// import type { Metadata } from "next";
// import { Geist } from "next/font/google";
import "../../app/globals.css";
import Header from "@/components/header";
import React from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Project X",
//   description: "Generated by create next app",
// };

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body className={`${geistSans.variable}  antialiased`}>
    //     <Header />
    //     <main className={`data-[state=open]:animate-collapsible-down `}>
    //       {children}
    //     </main>
    //   </body>
    // </html>
    <>
      <Header />
      <div className="main-layout data-[state=open]:animate-collapsible-down">{children}</div>
    </>
  );
}
