import { Metadata } from "next";
import CompanyClient from "./components/CompanyClient";
export const metadata: Metadata = {
  title: "Danh sách công ty | Project X",
  description: "Generated by create next app",
};
const ListCompanyPage = () => {
  return (
    <>
      <CompanyClient />
    </>
  );
};

export default ListCompanyPage;
