import { Skeleton } from "@/components/ui/skeleton";
import React, { Suspense } from "react";
import AppointmentClientCandidate from "./components/AppointmentClient";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Danh sách lịch hẹn | Project X",
  description: "Generated by create next app",
};
const AppointmentPage = () => {
  return (
    <Suspense
      fallback={
        <div className="pt-14 pl-8 pr-8 w-full">
          <div className="container w-full mx-auto p-4 space-y-4 bg-accent">
            <Skeleton className="h-10 w-[300px]" />
            <Skeleton className="h-[400px] w-full" />
          </div>
        </div>
      }
    >
      <AppointmentClientCandidate />;
    </Suspense>
  );
};

export default AppointmentPage;
