import Header from "@/app/(routes)/(components)/header";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Tạo CV  | Project X",
  description: "Generated by create next app",
};
const CreateCvLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <div className="min-h-screen">
      <Header />
      <div className="">{children}</div>
    </div>
  );
};

export default CreateCvLayout;
