import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import React from "react";
import Providers from "./(routes)/providers";
import QueryProvider from "./(routes)/(components)/QueryProvider";
import { Toaster } from "@/components/ui/sonner";
import AuthWrapper from "./(routes)/(components)/AuthWraper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tìm kiếm việc làm 24h với Project X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}  antialiased `}>
        <main>
          <QueryProvider>
            <Providers>
              <AuthWrapper>{children}</AuthWrapper>
              <Toaster position="top-right" richColors closeButton />
            </Providers>
          </QueryProvider>
        </main>
      </body>
    </html>
  );
}
