import AppointmentDetailClient from "@/app/(employer)/employer/appointments/[id]/components/AppointmentDetailClient";
import { Skeleton } from "@/components/ui/skeleton";
import { Metadata } from "next";
import React, { Suspense } from "react";
export const metadata: Metadata = {
  title: "Chi tiết lịch hẹn | Project X",
  description: "Generated by create next app",
};
const AppointmentDetailPage = () => {
  return (
    <Suspense
      fallback={
        <div className="pt-14 pl-8 pr-8 w-full">
          <div className="container w-full mx-auto p-4 space-y-4 bg-accent">
            <Skeleton className="h-10 w-[300px]" />
            <Skeleton className="h-[400px] w-full" />
          </div>
        </div>
      }
    >
      <AppointmentDetailClient />;
    </Suspense>
  );
};

export default AppointmentDetailPage;
