import { Metadata } from "next";
import CardSavedJos from "./components/CardSavedJos";
export const metadata: Metadata = {
  title: "Việc làm đã lưu | Project X",
  description: "Generated by create next app",
};
const SavedJobsPage = () => {
  return (
    <div className="bg-accent min-h-screen">
      <CardSavedJos />;
    </div>
  );
};

export default SavedJobsPage;
